import { useState, useMemo, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { usePackage, useCreatePackage, useUpdatePackage } from '../hooks/usePackages';
import { useFeatures } from '../hooks/useFeatures';
import { useUIStore } from '../stores/uiStore';
import { LoadingSpinner, Button, Input, Textarea } from '../components/ui';
import { packageSchema, PackageFormData } from '../lib/validations';


const PackageEditor = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const isEditing = !!id;
    const packageId = id ? parseInt(id, 10) : null;

    const [activeTab, setActiveTab] = useState<'basic' | 'features'>('basic');

    // React Query hooks
    const { data: pkg, isLoading: packageLoading } = usePackage(packageId);
    const { data: features = [], isLoading: featuresLoading } = useFeatures();

    const createMutation = useCreatePackage();
    const updateMutation = useUpdatePackage();
    const { addNotification } = useUIStore();

    // Group features for UI
    const sortedFeatures = useMemo(() => {
        return [...features].sort((a, b) => a.id - b.id);
    }, [features]);

    // React Hook Form
    const {
        register,
        handleSubmit,
        reset,
        setValue,
        watch,
        formState: { errors, isSubmitting },
    } = useForm<PackageFormData>({
        resolver: zodResolver(packageSchema),
        defaultValues: {
            name: '',
            price: 0,
            duration_days: 30,
            features: '',
            feature_ids: [],
            description: '',
        },
    });

    // Populate form when package data loads
    useEffect(() => {
        if (pkg) {
            let customBenefits = '';

            // Logic: Description column contains JSON array.
            // Items might be:
            // 1. "Akses Mandiri X..." (Summary string generated by system)
            // 2. "Benefit A" (Manual)
            // We need to filter out the summary string so it doesn't appear in the manual benefits box.

            if (pkg.description) {
                try {
                    const parsed = JSON.parse(pkg.description);
                    if (Array.isArray(parsed)) {
                        // Filter out items that look like the auto-generated summary
                        const benefitsOnly = parsed.filter(item => !item.startsWith('Akses Mandiri'));
                        customBenefits = benefitsOnly.join('\n');
                    } else {
                        // Fallback for old simple string descriptions
                        customBenefits = pkg.description;
                    }
                } catch {
                    customBenefits = pkg.description;
                }
            }

            reset({
                name: pkg.name,
                price: pkg.price,
                duration_days: pkg.duration_days,
                features: '',
                feature_ids: pkg.feature_ids || [],
                description: customBenefits,
            });
        }
    }, [pkg, features, reset]);

    const selectedFeatureIds = watch('feature_ids') || [];
    const watchedBenefits = watch('description');

    // Helper to generate the feature summary string
    const generateFeatureSummary = (selectedIds: number[]) => {
        if (selectedIds.length === 0) return null;

        const selectedFeatureNames = selectedIds
            .map(id => features.find(f => f.id === id)?.name)
            .filter(Boolean) as string[];

        // Check if ALL features are selected
        if (selectedIds.length === features.length && features.length > 0) {
            return "Akses Mandiri Semua Template Dokumen";
        }

        // Partial selection
        return `Akses Mandiri ${selectedIds.length} Template Dokumen (${selectedFeatureNames.join(', ')})`;
    };

    // JSON Preview Logic (Combines Features Summary + Benefits)
    const jsonPreview = useMemo(() => {
        // 1. Get Feature Summary
        const featureSummary = generateFeatureSummary(selectedFeatureIds);

        // 2. Get Manual Benefits
        const manualBenefits = watchedBenefits
            ? watchedBenefits.split('\n').filter(line => line.trim().length > 0)
            : [];

        // 3. Combine
        const combined = featureSummary
            ? [featureSummary, ...manualBenefits]
            : manualBenefits;

        return JSON.stringify(combined, null, 2);
    }, [watchedBenefits, selectedFeatureIds, features]);

    const handleFeatureToggle = (featureId: number) => {
        const current = selectedFeatureIds;
        if (current.includes(featureId)) {
            setValue('feature_ids', current.filter(id => id !== featureId));
        } else {
            setValue('feature_ids', [...current, featureId]);
        }
    };

    const onSubmit = async (data: PackageFormData) => {
        // Re-calculate the combined description for changes
        const featureSummary = generateFeatureSummary(data.feature_ids);

        const manualBenefits = data.description
            ? data.description.split('\n').filter(line => line.trim().length > 0)
            : [];

        const combined = featureSummary
            ? [featureSummary, ...manualBenefits]
            : manualBenefits;

        const finalDescription = JSON.stringify(combined);

        const payload = {
            name: data.name,
            price: Number(data.price),
            duration_days: Number(data.duration_days),
            feature_ids: data.feature_ids,
            features: '',
            description: finalDescription,
        };

        try {
            if (isEditing && packageId) {
                await updateMutation.mutateAsync({ id: packageId, ...payload });
                addNotification({
                    type: 'success',
                    title: 'Package Updated',
                    message: `${data.name} has been updated successfully.`,
                });
            } else {
                await createMutation.mutateAsync(payload);
                addNotification({
                    type: 'success',
                    title: 'Package Created',
                    message: `${data.name} has been created successfully.`,
                });
            }
            navigate('/packages');
        } catch {
            addNotification({
                type: 'error',
                title: 'Operation Failed',
                message: 'Failed to save package. Please try again.',
            });
        }
    };

    if (packageLoading && isEditing || featuresLoading) {
        return <LoadingSpinner size="lg" text="Loading editor..." icon="✏️" />;
    }

    return (
        <div className="space-y-6 animate-fade-in max-w-5xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" onClick={() => navigate('/packages')} icon="⬅️">
                        Back
                    </Button>
                    <div>
                        <h1 className="text-3xl font-black text-gray-900">
                            {isEditing ? `Edit ${pkg?.name || 'Package'}` : 'Create New Package'}
                        </h1>
                        <p className="text-gray-500">
                            {isEditing ? 'Update package details and features' : 'Configure a new subscription package'}
                        </p>
                    </div>
                </div>
            </div>

            <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-gray-100">
                {/* Tabs */}
                <div className="flex border-b bg-gray-50/50">
                    <button
                        className={`px-8 py-4 font-bold text-sm transition-all ${activeTab === 'basic'
                            ? 'bg-white border-b-2 border-purple-500 text-purple-600 shadow-sm'
                            : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
                            }`}
                        onClick={() => setActiveTab('basic')}
                    >
                        Basic Info
                    </button>
                    <button
                        className={`px-8 py-4 font-bold text-sm transition-all ${activeTab === 'features'
                            ? 'bg-white border-b-2 border-purple-500 text-purple-600 shadow-sm'
                            : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
                            }`}
                        onClick={() => setActiveTab('features')}
                    >
                        Features & Content
                    </button>
                </div>

                <form onSubmit={handleSubmit(onSubmit)} className="p-8 space-y-8">
                    {/* Basic Info Tab */}
                    {activeTab === 'basic' && (
                        <div className="space-y-6 animate-fade-in">
                            <div className="max-w-2xl">
                                <Input
                                    label="Package Name"
                                    icon="🏷️"
                                    placeholder="Enter package name"
                                    error={errors.name?.message}
                                    {...register('name')}
                                />
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-2xl">
                                <Input
                                    label="Price (IDR)"
                                    icon="💰"
                                    type="number"
                                    placeholder="50000"
                                    error={errors.price?.message}
                                    {...register('price', { valueAsNumber: true })}
                                />

                                <Input
                                    label="Duration (days)"
                                    icon="⏳"
                                    type="number"
                                    placeholder="30"
                                    error={errors.duration_days?.message}
                                    {...register('duration_days', { valueAsNumber: true })}
                                />
                            </div>
                        </div>
                    )}

                    {/* Features & Content Tab */}
                    {activeTab === 'features' && (
                        <div className="space-y-8 animate-fade-in">
                            {/* Feature Selection Grid */}
                            <div className="space-y-3">
                                <label className="block text-sm font-bold text-gray-700 flex items-center gap-2">
                                    <span>✨</span>
                                    Select Features
                                </label>

                                {errors.feature_ids && (
                                    <p className="text-red-500 text-xs font-semibold">{errors.feature_ids.message}</p>
                                )}

                                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 p-4 bg-gray-50 rounded-2xl border-2 border-gray-100 max-h-[500px] overflow-y-auto">
                                    {sortedFeatures.map(feature => {
                                        const isSelected = selectedFeatureIds.includes(feature.id);
                                        return (
                                            <div
                                                key={feature.id}
                                                onClick={() => handleFeatureToggle(feature.id)}
                                                className={`flex items-center p-3 rounded-xl cursor-pointer transition-all duration-200 border-2 ${isSelected
                                                    ? 'bg-purple-50 border-purple-500 shadow-md transform scale-[1.02]'
                                                    : 'bg-white border-transparent hover:border-gray-200'
                                                    }`}
                                            >
                                                <div className={`w-5 h-5 rounded-md flex items-center justify-center border-2 mr-3 transition-colors ${isSelected ? 'bg-purple-500 border-purple-500' : 'border-gray-300'
                                                    }`}>
                                                    {isSelected && <span className="text-white text-xs font-bold">✓</span>}
                                                </div>
                                                <div className="flex-1">
                                                    <p className={`text-sm font-semibold leading-tight ${isSelected ? 'text-purple-700' : 'text-gray-700'}`}>
                                                        {feature.name}
                                                    </p>
                                                    <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full mt-1 inline-block ${feature.status === 'premium' ? 'bg-amber-100 text-amber-700' : 'bg-green-100 text-green-700'}`}>
                                                        {feature.status}
                                                    </span>
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Description Preview & Override */}
                            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 border-t pt-8">
                                <div className="space-y-2">
                                    <label className="block text-sm font-bold text-gray-700 flex items-center gap-2">
                                        <span>📝</span>
                                        JSON Description Preview
                                    </label>
                                    <div className="bg-gray-900 text-green-400 p-6 rounded-2xl font-mono text-xs overflow-x-auto h-64 shadow-inner">
                                        <pre>{jsonPreview}</pre>
                                    </div>
                                    <p className="text-xs text-gray-500">
                                        This is the exact data that will be saved to the legacy description column.
                                    </p>
                                </div>

                                <div className="space-y-2">
                                    <label className="block text-sm font-bold text-gray-700 flex items-center gap-2">
                                        <span>✨</span>
                                        Additional Benefits (Manfaat)
                                    </label>
                                    <Textarea
                                        // label="Manual Override"
                                        // icon="✏️"
                                        placeholder={`Enter ADDITIONAL benefits here, one per line.\nThese will be ADDED to the selected features above.\n\nExample:\nFree Template Kops Surat\nFree Design Brosur\nSupport 24/7`}
                                        rows={12}
                                        className="h-64 font-mono text-sm"
                                        error={errors.description?.message}
                                        {...register('description')}
                                    />
                                    <p className="text-xs text-gray-500 italic">
                                        * These benefits will be combined with selected features in the final description.
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}

                    <div className="flex justify-end gap-4 pt-4 border-t">
                        <Button
                            type="button"
                            variant="secondary"
                            onClick={() => navigate('/packages')}
                            className="w-32"
                        >
                            Cancel
                        </Button>
                        <Button
                            type="submit"
                            variant="primary"
                            loading={isSubmitting || createMutation.isPending || updateMutation.isPending}
                            className="w-40"
                            size="lg"
                        >
                            {isEditing ? 'Save Changes' : 'Create Package'}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default PackageEditor;
